// <auto-generated />
using Hoodie.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoodie.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hoodie.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Supreme",
                            Description = "Supreme moves away from eye-catching branding with this dark grey hoodie, instead opting for a small box logo to the front. This allows for a more pared-back look for the off-duty piece.",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/17/75/97/72/17759772_37390075_1000.jpg",
                            Name = "Supreme Box Logo Black Hoodie",
                            Price = 431.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Supreme",
                            Description = "The Supreme Swarovski box logo hoodie, in navy blue, is one of three colours for the special edition hooded sweatshirt featuring the streetwear brand’s iconic logo constructed in shining crystals. Supreme enlisted Swarovski to help them celebrate their 25th anniversary in 2019 with this luxurious take on the box logo. The design features 1,201 Swarovski red and clear crystals that form the logo. The hoodie is crafted with Supreme's high-quality fleece.",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/16/50/65/14165065_40949812_1000.jpg",
                            Name = "Supreme x Swarovski Box Logo Hoodie",
                            Price = 1790.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Supreme",
                            Description = "Supreme's signature blend of relaxed silhouettes and bold branding is reflected in the design of this hoodie. Crafted from cotton, it is punctuated with the label's signature Box Logo to the front.",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/17/75/78/45/17757845_37966486_1000.jpg",
                            Name = "Supreme Box Logo White Hoodie",
                            Price = 488.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
